export const BRANCHES = [
    "Computer Science & Engineering (CSE)",
    "Artificial Intelligence & Machine Learning (AI&ML)",
    "Data Science",
    "Information Technology (IT)",
    "Electronics & Communication Engineering (ECE)",
    "Electrical & Electronics Engineering (EEE)",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biotechnology",
    "B.Sc (Bachelor of Science)",
    "B.Com (Bachelor of Commerce)",
    "BBA (Business Administration)",
    "BCA (Computer Applications)",
    "MBA (Master of Business Administration)",
    "MCA (Master of Computer Applications)",
    "M.Tech (Master of Technology)",
    "Pharmacy (B.Pharm/M.Pharm)",
    "Medical (MBBS/BDS)",
    "Law (LLB/BA LLB)",
    "Architecture (B.Arch)",
    "Arts (BA/MA)",
    "Other"
];
