export const BRANCHES = [
    "Computer Science & Engineering (CSE)",
    "Artificial Intelligence & Machine Learning (AI&ML)",
    "Data Science",
    "Information Technology (IT)",
    "Electronics & Communication Engineering (ECE)",
    "Electrical & Electronics Engineering (EEE)",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biotechnology",
    "B.Sc (Bachelor of Science)",
    "B.Com (Bachelor of Commerce)",
    "BBA (Business Administration)",
    "BCA (Computer Applications)",
    "MBA (Master of Business Administration)",
    "MCA (Master of Computer Applications)",
    "M.Tech (Master of Technology)",
    "Pharmacy (B.Pharm/M.Pharm)",
    "Medical (MBBS/BDS)",
    "Law (LLB/BA LLB)",
    "Architecture (B.Arch)",
    "Arts (BA/MA)",
    "Other"
];

export const INDIAN_STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Lakshadweep",
    "Delhi",
    "Puducherry",
    "Ladakh",
    "Jammu and Kashmir",
];
