/**
 * Data for international registration: countries with dial codes and ISO codes for flags,
 * institutions (universities), and programs of study.
 */

export interface CountryWithDial {
  name: string;
  dialCode: string;
  /** ISO 3166-1 alpha-2 (e.g. US, IN) for flag emoji */
  iso2: string;
  /** ISO 3166-1 alpha-3 (e.g. USA, IND, GBR) for short display */
  iso3: string;
}

/** Returns Unicode flag emoji for ISO 2-letter country code (e.g. "US" → 🇺🇸) */
export function getCountryFlag(iso2: string): string {
  if (!iso2 || iso2.length !== 2) return "";
  const u = iso2.toUpperCase();
  return String.fromCodePoint(
    ...u.split("").map((c) => 0x1f1e6 - 65 + c.charCodeAt(0))
  );
}

// ISO 3166-1 alpha-3 for short display (IND, USA, GBR, AFG, PAK, etc.)
const ISO3: Record<string, string> = {
  AF: "AFG", AL: "ALB", DZ: "DZA", AD: "AND", AO: "AGO", AR: "ARG", AM: "ARM", AU: "AUS", AT: "AUT", AZ: "AZE",
  BH: "BHR", BD: "BGD", BY: "BLR", BE: "BEL", BZ: "BLZ", BJ: "BEN", BT: "BTN", BO: "BOL", BA: "BIH", BW: "BWA",
  BR: "BRA", BN: "BRN", BG: "BGR", BF: "BFA", KH: "KHM", CM: "CMR", CA: "CAN", CL: "CHL", CN: "CHN", CO: "COL",
  CR: "CRI", HR: "HRV", CU: "CUB", CY: "CYP", CZ: "CZE", DK: "DNK", EC: "ECU", EG: "EGY", EE: "EST", ET: "ETH",
  FI: "FIN", FR: "FRA", GE: "GEO", DE: "DEU", GH: "GHA", GR: "GRC", GT: "GTM", HK: "HKG", HU: "HUN", IS: "ISL",
  IN: "IND", ID: "IDN", IR: "IRN", IQ: "IRQ", IE: "IRL", IL: "ISR", IT: "ITA", JM: "JAM", JP: "JPN", JO: "JOR",
  KZ: "KAZ", KE: "KEN", KR: "KOR", KW: "KWT", KG: "KGZ", LV: "LVA", LB: "LBN", LY: "LBY", LT: "LTU", LU: "LUX",
  MO: "MAC", MY: "MYS", MV: "MDV", MT: "MLT", MU: "MUS", MX: "MEX", MD: "MDA", MC: "MCO", MN: "MNG", ME: "MNE",
  MA: "MAR", MZ: "MOZ", MM: "MMR", NP: "NPL", NL: "NLD", NZ: "NZL", NG: "NGA", MK: "MKD", NO: "NOR", OM: "OMN",
  PK: "PAK", PS: "PSE", PA: "PAN", PY: "PRY", PE: "PER", PH: "PHL", PL: "POL", PT: "PRT", PR: "PRI", QA: "QAT",
  RO: "ROU", RU: "RUS", RW: "RWA", SA: "SAU", SN: "SEN", RS: "SRB", SG: "SGP", SK: "SVK", SI: "SVN", ZA: "ZAF",
  ES: "ESP", LK: "LKA", SD: "SDN", SE: "SWE", CH: "CHE", SY: "SYR", TW: "TWN", TJ: "TJK", TZ: "TZA", TH: "THA",
  TN: "TUN", TR: "TUR", TM: "TKM", UG: "UGA", UA: "UKR", AE: "ARE", GB: "GBR", US: "USA", UY: "URY", UZ: "UZB",
  VE: "VEN", VN: "VNM", YE: "YEM", ZM: "ZMB", ZW: "ZWE",
};

export interface CountryWithDial {
  name: string;
  dialCode: string;
  iso2: string;
  iso3: string;
}

function getIso3(iso2: string): string {
  return ISO3[iso2.toUpperCase()] || iso2.toUpperCase();
}

/** Get short display code for phone selector: IND, USA, GBR, AFG, PAK */
export function getCountryCode(iso2: string): string {
  return getIso3(iso2);
}

// Countries with dial codes and ISO codes – alphabetical by name
export const COUNTRIES_WITH_DIAL: CountryWithDial[] = [
  { name: "Afghanistan", dialCode: "+93", iso2: "AF", iso3: "AFG" },
  { name: "Albania", dialCode: "+355", iso2: "AL", iso3: "ALB" },
  { name: "Algeria", dialCode: "+213", iso2: "DZ", iso3: "DZA" },
  { name: "Andorra", dialCode: "+376", iso2: "AD", iso3: "AND" },
  { name: "Angola", dialCode: "+244", iso2: "AO", iso3: "AGO" },
  { name: "Argentina", dialCode: "+54", iso2: "AR", iso3: "ARG" },
  { name: "Armenia", dialCode: "+374", iso2: "AM", iso3: "ARM" },
  { name: "Australia", dialCode: "+61", iso2: "AU", iso3: "AUS" },
  { name: "Austria", dialCode: "+43", iso2: "AT", iso3: "AUT" },
  { name: "Azerbaijan", dialCode: "+994", iso2: "AZ", iso3: "AZE" },
  { name: "Bahrain", dialCode: "+973", iso2: "BH", iso3: "BHR" },
  { name: "Bangladesh", dialCode: "+880", iso2: "BD", iso3: "BGD" },
  { name: "Belarus", dialCode: "+375", iso2: "BY", iso3: "BLR" },
  { name: "Belgium", dialCode: "+32", iso2: "BE", iso3: "BEL" },
  { name: "Belize", dialCode: "+501", iso2: "BZ", iso3: "BLZ" },
  { name: "Benin", dialCode: "+229", iso2: "BJ", iso3: "BEN" },
  { name: "Bhutan", dialCode: "+975", iso2: "BT", iso3: "BTN" },
  { name: "Bolivia", dialCode: "+591", iso2: "BO", iso3: "BOL" },
  { name: "Bosnia and Herzegovina", dialCode: "+387", iso2: "BA", iso3: "BIH" },
  { name: "Botswana", dialCode: "+267", iso2: "BW", iso3: "BWA" },
  { name: "Brazil", dialCode: "+55", iso2: "BR", iso3: "BRA" },
  { name: "Brunei", dialCode: "+673", iso2: "BN", iso3: "BRN" },
  { name: "Bulgaria", dialCode: "+359", iso2: "BG", iso3: "BGR" },
  { name: "Burkina Faso", dialCode: "+226", iso2: "BF", iso3: "BFA" },
  { name: "Cambodia", dialCode: "+855", iso2: "KH", iso3: "KHM" },
  { name: "Cameroon", dialCode: "+237", iso2: "CM", iso3: "CMR" },
  { name: "Canada", dialCode: "+1", iso2: "CA", iso3: "CAN" },
  { name: "Chile", dialCode: "+56", iso2: "CL", iso3: "CHL" },
  { name: "China", dialCode: "+86", iso2: "CN", iso3: "CHN" },
  { name: "Colombia", dialCode: "+57", iso2: "CO", iso3: "COL" },
  { name: "Costa Rica", dialCode: "+506", iso2: "CR", iso3: "CRI" },
  { name: "Croatia", dialCode: "+385", iso2: "HR", iso3: "HRV" },
  { name: "Cuba", dialCode: "+53", iso2: "CU", iso3: "CUB" },
  { name: "Cyprus", dialCode: "+357", iso2: "CY", iso3: "CYP" },
  { name: "Czech Republic", dialCode: "+420", iso2: "CZ", iso3: "CZE" },
  { name: "Denmark", dialCode: "+45", iso2: "DK", iso3: "DNK" },
  { name: "Ecuador", dialCode: "+593", iso2: "EC", iso3: "ECU" },
  { name: "Egypt", dialCode: "+20", iso2: "EG", iso3: "EGY" },
  { name: "Estonia", dialCode: "+372", iso2: "EE", iso3: "EST" },
  { name: "Ethiopia", dialCode: "+251", iso2: "ET", iso3: "ETH" },
  { name: "Finland", dialCode: "+358", iso2: "FI", iso3: "FIN" },
  { name: "France", dialCode: "+33", iso2: "FR", iso3: "FRA" },
  { name: "Georgia", dialCode: "+995", iso2: "GE", iso3: "GEO" },
  { name: "Germany", dialCode: "+49", iso2: "DE", iso3: "DEU" },
  { name: "Ghana", dialCode: "+233", iso2: "GH", iso3: "GHA" },
  { name: "Greece", dialCode: "+30", iso2: "GR", iso3: "GRC" },
  { name: "Guatemala", dialCode: "+502", iso2: "GT", iso3: "GTM" },
  { name: "Hong Kong", dialCode: "+852", iso2: "HK", iso3: "HKG" },
  { name: "Hungary", dialCode: "+36", iso2: "HU", iso3: "HUN" },
  { name: "Iceland", dialCode: "+354", iso2: "IS", iso3: "ISL" },
  { name: "India", dialCode: "+91", iso2: "IN", iso3: "IND" },
  { name: "Indonesia", dialCode: "+62", iso2: "ID", iso3: "IDN" },
  { name: "Iran", dialCode: "+98", iso2: "IR", iso3: "IRN" },
  { name: "Iraq", dialCode: "+964", iso2: "IQ", iso3: "IRQ" },
  { name: "Ireland", dialCode: "+353", iso2: "IE", iso3: "IRL" },
  { name: "Israel", dialCode: "+972", iso2: "IL", iso3: "ISR" },
  { name: "Italy", dialCode: "+39", iso2: "IT", iso3: "ITA" },
  { name: "Jamaica", dialCode: "+1876", iso2: "JM", iso3: "JAM" },
  { name: "Japan", dialCode: "+81", iso2: "JP", iso3: "JPN" },
  { name: "Jordan", dialCode: "+962", iso2: "JO", iso3: "JOR" },
  { name: "Kazakhstan", dialCode: "+7", iso2: "KZ", iso3: "KAZ" },
  { name: "Kenya", dialCode: "+254", iso2: "KE", iso3: "KEN" },
  { name: "South Korea", dialCode: "+82", iso2: "KR", iso3: "KOR" },
  { name: "Kuwait", dialCode: "+965", iso2: "KW", iso3: "KWT" },
  { name: "Kyrgyzstan", dialCode: "+996", iso2: "KG", iso3: "KGZ" },
  { name: "Latvia", dialCode: "+371", iso2: "LV", iso3: "LVA" },
  { name: "Lebanon", dialCode: "+961", iso2: "LB", iso3: "LBN" },
  { name: "Libya", dialCode: "+218", iso2: "LY", iso3: "LBY" },
  { name: "Lithuania", dialCode: "+370", iso2: "LT", iso3: "LTU" },
  { name: "Luxembourg", dialCode: "+352", iso2: "LU", iso3: "LUX" },
  { name: "Macau", dialCode: "+853", iso2: "MO", iso3: "MAC" },
  { name: "Malaysia", dialCode: "+60", iso2: "MY", iso3: "MYS" },
  { name: "Maldives", dialCode: "+960", iso2: "MV", iso3: "MDV" },
  { name: "Malta", dialCode: "+356", iso2: "MT", iso3: "MLT" },
  { name: "Mauritius", dialCode: "+230", iso2: "MU", iso3: "MUS" },
  { name: "Mexico", dialCode: "+52", iso2: "MX", iso3: "MEX" },
  { name: "Moldova", dialCode: "+373", iso2: "MD", iso3: "MDA" },
  { name: "Monaco", dialCode: "+377", iso2: "MC", iso3: "MCO" },
  { name: "Mongolia", dialCode: "+976", iso2: "MN", iso3: "MNG" },
  { name: "Montenegro", dialCode: "+382", iso2: "ME", iso3: "MNE" },
  { name: "Morocco", dialCode: "+212", iso2: "MA", iso3: "MAR" },
  { name: "Mozambique", dialCode: "+258", iso2: "MZ", iso3: "MOZ" },
  { name: "Myanmar", dialCode: "+95", iso2: "MM", iso3: "MMR" },
  { name: "Nepal", dialCode: "+977", iso2: "NP", iso3: "NPL" },
  { name: "Netherlands", dialCode: "+31", iso2: "NL", iso3: "NLD" },
  { name: "New Zealand", dialCode: "+64", iso2: "NZ", iso3: "NZL" },
  { name: "Nigeria", dialCode: "+234", iso2: "NG", iso3: "NGA" },
  { name: "North Macedonia", dialCode: "+389", iso2: "MK", iso3: "MKD" },
  { name: "Norway", dialCode: "+47", iso2: "NO", iso3: "NOR" },
  { name: "Oman", dialCode: "+968", iso2: "OM", iso3: "OMN" },
  { name: "Pakistan", dialCode: "+92", iso2: "PK", iso3: "PAK" },
  { name: "Palestine", dialCode: "+970", iso2: "PS", iso3: "PSE" },
  { name: "Panama", dialCode: "+507", iso2: "PA", iso3: "PAN" },
  { name: "Paraguay", dialCode: "+595", iso2: "PY", iso3: "PRY" },
  { name: "Peru", dialCode: "+51", iso2: "PE", iso3: "PER" },
  { name: "Philippines", dialCode: "+63", iso2: "PH", iso3: "PHL" },
  { name: "Poland", dialCode: "+48", iso2: "PL", iso3: "POL" },
  { name: "Portugal", dialCode: "+351", iso2: "PT", iso3: "PRT" },
  { name: "Puerto Rico", dialCode: "+1787", iso2: "PR", iso3: "PRI" },
  { name: "Qatar", dialCode: "+974", iso2: "QA", iso3: "QAT" },
  { name: "Romania", dialCode: "+40", iso2: "RO", iso3: "ROU" },
  { name: "Russia", dialCode: "+7", iso2: "RU", iso3: "RUS" },
  { name: "Rwanda", dialCode: "+250", iso2: "RW", iso3: "RWA" },
  { name: "Saudi Arabia", dialCode: "+966", iso2: "SA", iso3: "SAU" },
  { name: "Senegal", dialCode: "+221", iso2: "SN", iso3: "SEN" },
  { name: "Serbia", dialCode: "+381", iso2: "RS", iso3: "SRB" },
  { name: "Singapore", dialCode: "+65", iso2: "SG", iso3: "SGP" },
  { name: "Slovakia", dialCode: "+421", iso2: "SK", iso3: "SVK" },
  { name: "Slovenia", dialCode: "+386", iso2: "SI", iso3: "SVN" },
  { name: "South Africa", dialCode: "+27", iso2: "ZA", iso3: "ZAF" },
  { name: "Spain", dialCode: "+34", iso2: "ES", iso3: "ESP" },
  { name: "Sri Lanka", dialCode: "+94", iso2: "LK", iso3: "LKA" },
  { name: "Sudan", dialCode: "+249", iso2: "SD", iso3: "SDN" },
  { name: "Sweden", dialCode: "+46", iso2: "SE", iso3: "SWE" },
  { name: "Switzerland", dialCode: "+41", iso2: "CH", iso3: "CHE" },
  { name: "Syria", dialCode: "+963", iso2: "SY", iso3: "SYR" },
  { name: "Taiwan", dialCode: "+886", iso2: "TW", iso3: "TWN" },
  { name: "Tajikistan", dialCode: "+992", iso2: "TJ", iso3: "TJK" },
  { name: "Tanzania", dialCode: "+255", iso2: "TZ", iso3: "TZA" },
  { name: "Thailand", dialCode: "+66", iso2: "TH", iso3: "THA" },
  { name: "Tunisia", dialCode: "+216", iso2: "TN", iso3: "TUN" },
  { name: "Turkey", dialCode: "+90", iso2: "TR", iso3: "TUR" },
  { name: "Turkmenistan", dialCode: "+993", iso2: "TM", iso3: "TKM" },
  { name: "Uganda", dialCode: "+256", iso2: "UG", iso3: "UGA" },
  { name: "Ukraine", dialCode: "+380", iso2: "UA", iso3: "UKR" },
  { name: "United Arab Emirates", dialCode: "+971", iso2: "AE", iso3: "ARE" },
  { name: "United Kingdom", dialCode: "+44", iso2: "GB", iso3: "GBR" },
  { name: "United States", dialCode: "+1", iso2: "US", iso3: "USA" },
  { name: "Uruguay", dialCode: "+598", iso2: "UY", iso3: "URY" },
  { name: "Uzbekistan", dialCode: "+998", iso2: "UZ", iso3: "UZB" },
  { name: "Venezuela", dialCode: "+58", iso2: "VE", iso3: "VEN" },
  { name: "Vietnam", dialCode: "+84", iso2: "VN", iso3: "VNM" },
  { name: "Yemen", dialCode: "+967", iso2: "YE", iso3: "YEM" },
  { name: "Zambia", dialCode: "+260", iso2: "ZM", iso3: "ZMB" },
  { name: "Zimbabwe", dialCode: "+263", iso2: "ZW", iso3: "ZWE" },
];

// Programs of study – main categories only (no sub-types)
export const PROGRAMS_OF_STUDY = [
  "Engineering",
  "Management",
  "Business Administration",
  "Computer Science",
  "Arts & Humanities",
  "Law",
  "Medicine / Health Sciences",
  "Architecture",
  "Science",
  "Pharmacy",
  "Fine Arts",
  "Economics",
  "Political Science",
  "Psychology",
  "Social Sciences",
  "Liberal Arts",
  "Biotechnology",
  "Other",
];

// Curated list of well-known institutions (searchable) – user can type "Other" and enter custom
export const INSTITUTIONS_LIST = [
  "Massachusetts Institute of Technology (MIT)",
  "Stanford University",
  "Harvard University",
  "University of Cambridge",
  "University of Oxford",
  "California Institute of Technology (Caltech)",
  "ETH Zurich",
  "University of California, Berkeley",
  "Imperial College London",
  "University of Chicago",
  "National University of Singapore (NUS)",
  "Nanyang Technological University (NTU)",
  "University of Toronto",
  "University of Melbourne",
  "University of Sydney",
  "University of Hong Kong",
  "Tsinghua University",
  "Peking University",
  "University of Tokyo",
  "Kyoto University",
  "Seoul National University",
  "KAIST",
  "Indian Institute of Technology (IIT) - Various",
  "Indian Institute of Science (IISc)",
  "BITS Pilani",
  "Delhi University",
  "University of Mumbai",
  "University of British Columbia",
  "McGill University",
  "University of Waterloo",
  "Monash University",
  "University of New South Wales",
  "Australian National University",
  "University of Edinburgh",
  "University of Manchester",
  "University College London (UCL)",
  "London School of Economics (LSE)",
  "Technical University of Munich",
  "Ludwig Maximilian University of Munich",
  "Heidelberg University",
  "Sorbonne University",
  "École Polytechnique",
  "Delft University of Technology",
  "University of Amsterdam",
  "KU Leuven",
  "University of Copenhagen",
  "KTH Royal Institute of Technology",
  "Chalmers University of Technology",
  "University of Helsinki",
  "University of Oslo",
  "University of Warsaw",
  "Charles University (Prague)",
  "Vienna University of Technology",
  "University of Barcelona",
  "Polytechnic University of Milan",
  "Sapienza University of Rome",
  "University of São Paulo",
  "Universidad de Buenos Aires",
  "Universidad Nacional Autónoma de México (UNAM)",
  "University of Cape Town",
  "American University of Beirut",
  "King Saud University",
  "King Abdullah University of Science and Technology (KAUST)",
  "Other",
];
